import type { ProductionWriteGuardInput } from "./types";

export function productionApprovalPhrase({
  dryRunHash,
  observedOpportunityCount,
  projectRef,
}: Pick<
  ProductionWriteGuardInput,
  "dryRunHash" | "observedOpportunityCount" | "projectRef"
>) {
  const hashPrefix = dryRunHash?.slice(0, 12) ?? "missing-dry-run";
  return `IMPORT ${hashPrefix} TO ${projectRef} AT COUNT ${observedOpportunityCount}`;
}

export function validateProductionWriteGuard(input: ProductionWriteGuardInput) {
  const errors: string[] = [];

  if (!input.commit) {
    errors.push("Commit mode is disabled; this run is dry-run only.");
  }
  if (input.projectRef !== input.expectedProjectRef) {
    errors.push(
      `Project ref mismatch: expected ${input.expectedProjectRef}, observed ${input.projectRef}.`,
    );
  }
  if (input.database !== input.expectedDatabase) {
    errors.push(
      `Database mismatch: expected ${input.expectedDatabase}, observed ${input.database}.`,
    );
  }
  if (input.schema !== input.expectedSchema) {
    errors.push(
      `Schema mismatch: expected ${input.expectedSchema}, observed ${input.schema}.`,
    );
  }
  if (!input.dryRunHash || !/^[a-f0-9]{64}$/i.test(input.dryRunHash)) {
    errors.push("A valid SHA-256 dry-run report hash is required.");
  } else if (input.dryRunHash !== input.expectedDryRunHash) {
    errors.push(
      "Dry-run hash does not match the plan generated by this execution. Re-run the dry run and obtain approval for the new hash.",
    );
  }
  if (input.expectedOpportunityCount == null) {
    errors.push("Expected pre-import Opportunity row count is required.");
  } else if (
    input.expectedOpportunityCount !== input.observedOpportunityCount
  ) {
    errors.push(
      `Opportunity count changed: expected ${input.expectedOpportunityCount}, observed ${input.observedOpportunityCount}. Re-run the dry run.`,
    );
  }

  if (input.environment === "production") {
    if (!input.allowProduction) {
      errors.push("Production writes require --allow-production.");
    }
    const expectedPhrase = productionApprovalPhrase(input);
    if (input.approvalPhrase !== expectedPhrase) {
      errors.push(`Production approval phrase must equal: ${expectedPhrase}`);
    }
  }

  return {
    allowed: errors.length === 0,
    errors,
  };
}
